"""Turn validated proposals into a DRAFT rule file under rules/np/proposed/ (never loaded).

A reviewer checks each change against the cited page, edits statuses, then moves the file into
rules/np/ to activate it. Comments and layout of the base file are preserved.
"""

from __future__ import annotations

import io
import json
from datetime import timedelta
from pathlib import Path

import nepali_datetime
from ruamel.yaml import YAML

from app.engine.gate import fy_start_ad
from app.engine.rules import RULES_DIR, RuleFile, RuleSet

PROPOSED_DIR = RULES_DIR / "np" / "proposed"


def _yaml() -> YAML:
    y = YAML()
    y.preserve_quotes = True
    y.width = 120
    return y


def apply_changes(
    base: RuleSet,
    changes: list,
    *,
    source: dict | None = None,
    effective_from_bs: str | None = None,
) -> tuple[str, RuleSet]:
    """Apply ProposedChange-like objects (param, proposed_value_json, page) to `base`.

    source: {"key", "title", "url", "sha256"} for the document the changes come from.
    effective_from_bs: "YYYY-MM-DD" (BS). A date in a later FY creates the next FY's v1;
    a date inside the base FY creates base.version + 1 starting that day.
    """
    y = _yaml()
    doc = y.load(base.path.read_text(encoding="utf-8"))

    if source:
        doc["sources"][source["key"]] = {"title": source["title"], "url": source["url"], "sha256": source["sha256"]}
    for ch in changes:
        p = doc["params"][ch.param]
        p["value"] = json.loads(ch.proposed_value_json)
        p["status"] = "needs_review"
        p["ref"] = f"{p['ref']} — PROPOSED from p.{ch.page}, verify"
        if source:
            p["src"] = source["key"]

    doc["version"] = base.raw.version + 1
    if effective_from_bs:
        start = nepali_datetime.datetime.strptime(effective_from_bs, "%Y-%m-%d").date().to_datetime_date()
        if start > base.effective_to:  # next fiscal year
            bs_year = nepali_datetime.date.from_datetime_date(start).year
            if nepali_datetime.date.from_datetime_date(start).month < 4:
                bs_year -= 1
            doc["fiscal_year"] = f"{bs_year}/{(bs_year + 1) % 100:02d}"
            doc["version"] = 1
            doc["effective_from"] = fy_start_ad(bs_year)
            doc["effective_to"] = fy_start_ad(bs_year + 1) - timedelta(days=1)
        elif start > base.effective_from:  # mid-year amendment
            doc["effective_from"] = start
    doc["review"]["status"] = "draft"
    doc["review"]["reviewed_by"] = None
    doc["review"]["reviewed_on"] = None

    buf = io.StringIO()
    y.dump(doc, buf)
    text = buf.getvalue()
    plain = YAML(typ="safe").load(text)
    return text, RuleSet(RuleFile.model_validate(plain), base.path)  # raises if the change breaks the schema


def write_draft(text: str, rules: RuleSet, out_dir: Path | None = None) -> Path:
    out_dir = out_dir or PROPOSED_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{rules.fiscal_year.replace('/', '-')}.v{rules.raw.version}.yaml"
    header = (
        "# DRAFT generated by the rule watcher. NOT ACTIVE.\n"
        "# Verify every PROPOSED value against the cited page, then move this file to rules/np/.\n"
    )
    path.write_text(header + text, encoding="utf-8")
    return path
