"""employee payslip details and TDS start policy

Revision ID: 0b03bf7b6a12
Revises: e7af8786ef89
Create Date: 2026-10-10 22:39:52.625846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b03bf7b6a12'
down_revision: Union[str, Sequence[str], None] = 'e7af8786ef89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=7), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year')
    )
    op.create_index(op.f('ix_tds_policies_company_id'), 'tds_policies', ['company_id'], unique=False)
    op.add_column('employees', sa.Column('department', sa.String(length=120), nullable=True))
    op.add_column('employees', sa.Column('designation', sa.String(length=120), nullable=True))
    op.add_column('employees', sa.Column('cit_number', sa.String(length=40), nullable=True))
    op.add_column('employees', sa.Column('ssf_number', sa.String(length=40), nullable=True))
    op.add_column('employees', sa.Column('bank_account', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'bank_account')
    op.drop_column('employees', 'ssf_number')
    op.drop_column('employees', 'cit_number')
    op.drop_column('employees', 'designation')
    op.drop_column('employees', 'department')
    op.drop_index(op.f('ix_tds_policies_company_id'), table_name='tds_policies')
    op.drop_table('tds_policies')
    # ### end Alembic commands ###
