"""initial schema

Revision ID: a39e7b0b508d
Revises: 
Create Date: 2026-10-08 00:01:46.569196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39e7b0b508d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('on', sa.Date(), nullable=False),
    sa.Column('buy', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sell', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'on', 'source', 'company_id', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_fx_rates_company_id'), 'fx_rates', ['company_id'], unique=False)
    op.create_index(op.f('ix_fx_rates_currency'), 'fx_rates', ['currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_on'), 'fx_rates', ['on'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'VIEWER', name='role', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id')
    )
    op.create_index(op.f('ix_memberships_company_id'), 'memberships', ['company_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=7), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', name='runstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rule_set', sa.String(length=40), nullable=True),
    sa.Column('rule_review_status', sa.String(length=20), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('acknowledged_unverified', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('finalized_by', sa.Integer(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'month')
    )
    op.create_index(op.f('ix_payroll_runs_company_id'), 'payroll_runs', ['company_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basic', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recurring_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recurring_basic', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ssf_employee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ssf_employer', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_retirement', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tds', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('projected_annual_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('projected_taxable_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'employee_id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_run_id'), 'payslips', ['run_id'], unique=False)
    op.create_table('run_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_adjustments_run_id'), 'run_adjustments', ['run_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('cit_monthly', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_retirement_monthly', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'effective_from')
    )
    op.create_index(op.f('ix_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=False)
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=7), nullable=False),
    sa.Column('resident', sa.Boolean(), nullable=False),
    sa.Column('filing', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('ssf_enrolled', sa.Boolean(), nullable=False),
    sa.Column('approved_pension', sa.Boolean(), nullable=False),
    sa.Column('remote_area', sa.String(length=1), nullable=True),
    sa.Column('income_only_from_employment', sa.Boolean(), nullable=False),
    sa.Column('life_insurance_premium', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('health_insurance_premium', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('building_insurance_premium', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('donation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'fiscal_year')
    )
    op.create_index(op.f('ix_tax_profiles_employee_id'), 'tax_profiles', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_profiles_employee_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    op.drop_index(op.f('ix_salary_structures_employee_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_run_adjustments_run_id'), table_name='run_adjustments')
    op.drop_table('run_adjustments')
    op.drop_index(op.f('ix_payslips_run_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payroll_runs_company_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_memberships_company_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_fx_rates_on'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_company_id'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
