"""pay calendar, CIT mode, previous employer, imported runs

Revision ID: e7af8786ef89
Revises: cd8951a11d1b
Create Date: 2026-10-08 23:02:53.126165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7af8786ef89'
down_revision: Union[str, Sequence[str], None] = 'cd8951a11d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('pay_calendar', sa.String(length=2), server_default='bs', nullable=False))
    op.add_column('payroll_runs', sa.Column('source', sa.String(length=10), server_default='computed', nullable=False))
    op.add_column('payslips', sa.Column('share_num', sa.Integer(), server_default='1', nullable=False))
    op.add_column('payslips', sa.Column('share_den', sa.Integer(), server_default='1', nullable=False))
    op.add_column('payslips', sa.Column('projected_tax_without_cit', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('salary_structures', sa.Column('cit_mode', sa.String(length=10), server_default='fixed', nullable=False))
    op.add_column('tax_profiles', sa.Column('prior_income', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('tax_profiles', sa.Column('prior_retirement', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    op.add_column('tax_profiles', sa.Column('prior_tds', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_profiles', 'prior_tds')
    op.drop_column('tax_profiles', 'prior_retirement')
    op.drop_column('tax_profiles', 'prior_income')
    op.drop_column('salary_structures', 'cit_mode')
    op.drop_column('payslips', 'projected_tax_without_cit')
    op.drop_column('payslips', 'share_den')
    op.drop_column('payslips', 'share_num')
    op.drop_column('payroll_runs', 'source')
    op.drop_column('companies', 'pay_calendar')
    # ### end Alembic commands ###
